# -*- coding: utf-8 -*-
"""Abastecimento

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvBSwflsNQe68RJ6vCt_LXBnRc3pxrLh
"""

d = float(input('Digite o valor do diâmetro: '))
h = float(input('Digite o valor do comprimento: '))
PA = float(input('Valor do pedido do posto A: '))
PB = float(input('Valor do pedido do posto B: '))
PC = float(input('Valor do pedido do posto C: '))
r = d/2
volume = 3.14 * r**2 * h
volume = volume * 1000
if volume >= PA:
  print('Posto A foi abastecido.')
  volume = volume - PA
else:
  print('Posto A não foi abastecido.')

if volume >= PB:
  print('Posto B foi abastecido.')
  volume = volume - PB
else:
  print('Posto B não foi abastecido.')

if volume >= PC:
  print('Posto C foi abastecido.')
  volume = volume - PC
else:
  print('Posto C não foi abastecido.')